export const initConfigData = () => [
  {
    name: 'heart_rate',
    unit: 'BPM',
    value: null,
    min: null,
    max: null,
    text: null,
  },
  {
    name: 'blood_pressure',
    unit: 'mg/DL',
    value: null,
    min: null,
    max: null,
    text: null,
  },
  {
    name: 'blood_glucose',
    unit: 'mm/Hg',
    value: null,
    min: null,
    max: null,
    text: null,
  },
  {
    name: 'spO2',
    unit: '%',
    value: null,
    min: null,
    max: null,
    text: null,
  },
  {
    name: 'temperature',
    unit: '°C',
    value: null,
    min: null,
    max: null,
    text: null,
  },
];
